export const STEPS = [
  { id: 1, title: 'Solution Context', description: 'Project overview and stakeholders' },
  { id: 2, title: 'General', description: 'Generic metrics and cross-cutting concerns' },
  { id: 3, title: 'Business', description: 'Business capabilities and processes' },
  { id: 4, title: 'Application', description: 'Tech stack and patterns' },
  { id: 5, title: 'Integration', description: 'APIs and integration catalogue' },
  { id: 6, title: 'Data', description: 'Classification and lifecycle' },
  { id: 7, title: 'Infra-Technology', description: 'Environments and platform' },
  { id: 8, title: 'Engineering & DevSecOps', description: 'CI/CD and quality gates' },
  { id: 9, title: 'NFRs (Quality of Service)', description: 'Performance and reliability' },
]

export const ARTEFACT_TYPES = [
  { value: 't-doc', label: 'Doc', description: 'Document / Report' },
  { value: 't-diag', label: 'Diagram', description: 'Architecture diagram' },
  { value: 't-xls', label: 'Sheet', description: 'Spreadsheet / Register' },
  { value: 't-deck', label: 'Deck', description: 'Presentation' },
  { value: 't-log', label: 'Log', description: 'Log / Tracker' },
]

export const ARTEFACTS_BY_DOMAIN = {
  general: [
    { name: 'Architecture Principles Doc', type: 't-doc' },
    { name: 'RAID Log', type: 't-log' },
    { name: 'TCO / Budget Sheet', type: 't-xls' },
    { name: 'Roadmap Deck', type: 't-deck' },
    { name: 'Standards & Policies Doc', type: 't-doc' },
    { name: 'End User Feedback Report', type: 't-doc' },
  ],
  business: [
    { name: 'Business Case / Problem Statement', type: 't-doc' },
    { name: 'Business Requirements Doc (BRD)', type: 't-doc' },
    { name: 'Domain Model Diagram', type: 't-diag' },
    { name: 'Business NFRs Register', type: 't-xls' },
    { name: 'Operating Model Doc', type: 't-doc' },
    { name: 'Business Continuity Plan', type: 't-doc' },
  ],
  application: [
    { name: 'High Level Design (HLD)', type: 't-diag' },
    { name: 'App Architecture Diagram', type: 't-diag' },
    { name: 'Architecture Decision Records (ADRs)', type: 't-doc' },
    { name: 'Tech Debt Register', type: 't-xls' },
    { name: 'Runbooks & Ops Docs', type: 't-doc' },
  ],
  integration: [
    { name: 'Integration Catalogue (Sheet)', type: 't-xls' },
    { name: 'API / Interface Catalog', type: 't-doc' },
  ],
  data: [
    { name: 'Data Architecture Diagram', type: 't-diag' },
    { name: 'Data Classification Register', type: 't-xls' },
    { name: 'Data Governance Doc', type: 't-doc' },
  ],
  infrastructure: [
    { name: 'Infra Architecture Diagram', type: 't-diag' },
    { name: 'Capacity Plan (Sheet)', type: 't-xls' },
    { name: 'Platform Lifecycle Register', type: 't-xls' },
    { name: 'Infra Security Controls Doc', type: 't-doc' },
    { name: 'Automation & IaaC Runbook', type: 't-doc' },
  ],
  devsecops: [
    { name: 'CI-CD Pipeline Diagram', type: 't-diag' },
    { name: 'DevOps Metrics Dashboard / Sheet', type: 't-xls' },
    { name: 'Threat Model Document', type: 't-doc' },
    { name: 'SW Quality Metrics Report', type: 't-xls' },
    { name: 'Secure Code Review Report', type: 't-doc' },
  ],
  nfr: [
    { name: 'NFR Requirements Sheet', type: 't-xls' },
    { name: 'HA & DR Plan', type: 't-doc' },
    { name: 'Security Controls Register', type: 't-xls' },
    { name: 'Performance Baseline Report', type: 't-doc' },
  ],
}

export const CHECKLIST_ITEMS = {
  general: {
    'End User Voices': [
      { id: 'gen-euv-1', question: 'Top 10 concerns/issues impacting end users identified?' },
      { id: 'gen-euv-2', question: 'End user wish list aspirations documented?' },
      { id: 'gen-euv-3', question: 'Support tickets and incidents analyzed?' },
    ],
    'Strategy Impact': [
      { id: 'gen-strat-1', question: 'Change in business priority assessed?' },
      { id: 'gen-strat-2', question: 'Change in business model considered?' },
      { id: 'gen-strat-3', question: 'Change in target operating model evaluated?' },
      { id: 'gen-strat-4', question: 'Alignment to target architecture/roadmap verified?' },
    ],
    'Documentation': [
      { id: 'gen-doc-1', question: 'Adherence to architecture principles (Business, App, Data, Tech)?' },
      { id: 'gen-doc-2', question: 'Adherence to patterns, standards, policies?' },
      { id: 'gen-doc-3', question: 'Level of documentation adequate?' },
    ],
    'Process Adherence': [
      { id: 'gen-proc-1', question: 'Adherence to PtX process?' },
      { id: 'gen-proc-2', question: 'RAID logs and decision logs maintained?' },
      { id: 'gen-proc-3', question: 'Roadmap alignment verified?' },
      { id: 'gen-proc-4', question: 'Consolidation, Federation, Standardization considered?' },
    ],
    'Economics': [
      { id: 'gen-eco-1', question: 'Total cost of ownership calculated (Development, Maintenance, Operations)?' },
      { id: 'gen-eco-2', question: 'Budget alignment verified?' },
      { id: 'gen-eco-3', question: 'Opportunities for cost optimization identified?' },
    ],
  },
  business: {
    'What': [
      { id: 'bus-what-1', question: 'Business use cases, capabilities impacted documented?' },
      { id: 'bus-what-2', question: 'Growth/change plans defined?' },
      { id: 'bus-what-3', question: 'Domain model established?' },
      { id: 'bus-what-4', question: 'Service/Contract/Functions documented?' },
    ],
    'Business NFRs': [
      { id: 'bus-nfr-1', question: 'Security - User password specs/expiry/resets/locks defined?' },
      { id: 'bus-nfr-2', question: 'Performance & Scalability - Business functions/transaction metrics defined?' },
      { id: 'bus-nfr-3', question: 'Business continuity plan established?' },
      { id: 'bus-nfr-4', question: 'Analytics/Monetization considered?' },
    ],
    'Why': [
      { id: 'bus-why-1', question: 'Why this capability, app or service justified?' },
      { id: 'bus-why-2', question: 'Entry-exit criteria for business functions/metrics defined?' },
      { id: 'bus-why-3', question: 'Business case relevance or updates documented?' },
      { id: 'bus-why-4', question: 'Business level product lifecycle and roadmap alignment verified?' },
    ],
    'Who': [
      { id: 'bus-who-1', question: 'Actors, Users, Systems and entities involved/impacted identified?' },
      { id: 'bus-who-2', question: 'Roles, User groups involved/impacted documented?' },
      { id: 'bus-who-3', question: 'User geo/regions - Multi-time zones considered?' },
      { id: 'bus-who-4', question: 'Multilingual support required?' },
      { id: 'bus-who-5', question: 'Multi-currency support required?' },
    ],
    'Others': [
      { id: 'bus-oth-1', question: 'Operation Time - 24/7, Weekdays etc. defined?' },
      { id: 'bus-oth-2', question: 'Business change management plan established?' },
      { id: 'bus-oth-3', question: 'Target operating model defined?' },
      { id: 'bus-oth-4', question: 'Continuity plan documented?' },
      { id: 'bus-oth-5', question: 'Reporting and monetization strategy defined?' },
    ],
  },
  application: {
    'Metadata & Lifecycle': [
      { id: 'app-meta-1', question: 'COTS/Bespoke/Legacy classification documented?' },
      { id: 'app-meta-2', question: 'Monolith/Microservices architecture defined?' },
      { id: 'app-meta-3', question: 'Technology stack documented?' },
      { id: 'app-meta-4', question: 'Technology debt identified?' },
      { id: 'app-meta-5', question: 'Planned SW upgrade, platforms upgrade documented?' },
      { id: 'app-meta-6', question: 'Dependent Library EOS tracked?' },
      { id: 'app-meta-7', question: 'End of life, End of Support, License expiry documented?' },
    ],
    'Software Architecture': [
      { id: 'app-soft-1', question: 'Technology choices align to standards; upgrade path and SBOM?' },
      { id: 'app-soft-2', question: 'Versioning and backward compatibility; ADRs?' },
      { id: 'app-soft-3', question: 'Resilience patterns: timeouts, retries, circuit breakers, idempotency?' },
      { id: 'app-soft-4', question: 'Documentation currency: diagrams, ADRs, runbooks, ownership established?' },
    ],
    'Others (Application)': [
      { id: 'app-oth-1', question: 'Usability metrics defined?' },
      { id: 'app-oth-2', question: 'Audits/Logging implemented?' },
      { id: 'app-oth-3', question: 'Monitoring, Alerts configured?' },
      { id: 'app-oth-4', question: 'TCO – 3yrs, 5yrs calculated?' },
      { id: 'app-oth-5', question: 'Integrations – QoS defined?' },
      { id: 'app-oth-6', question: 'Distributed Cache required?' },
      { id: 'app-oth-7', question: 'Notifications/Events implemented?' },
      { id: 'app-oth-8', question: 'Scheduled Jobs/Batches documented?' },
    ],
  },
  integration: {
    'Interface Catalog': [
      { id: 'int-cat-1', question: 'Interface Catalog documented (SR, Provider, Consumer)?' },
      { id: 'int-cat-2', question: 'Pattern, Type, Method defined (API, File, MSG, Event)?' },
      { id: 'int-cat-3', question: 'Interaction style specified (Async/Batch/Sync/Real-time)?' },
      { id: 'int-cat-4', question: 'Frequency documented?' },
      { id: 'int-cat-5', question: 'Data flows described?' },
    ],
    'Interface Checks': [
      { id: 'int-check-1', question: 'Interface Catalog, Events, SLAs, Versioning (API, Files, MSGs)?' },
      { id: 'int-check-2', question: 'Consistent API design: resource modeling, errors, pagination, filtering; security scopes?' },
      { id: 'int-check-3', question: 'Event schemas, registry, compatibility rules; ordering/replay requirements?' },
      { id: 'int-check-4', question: 'Reliability: idempotency, throttling & rate limiting?' },
    ],
    'NFRs': [
      { id: 'int-nfr-1', question: 'Scalability requirements defined?' },
      { id: 'int-nfr-2', question: 'Security requirements specified?' },
      { id: 'int-nfr-3', question: 'Performance metrics defined?' },
      { id: 'int-nfr-4', question: 'Bandwidth requirements documented?' },
      { id: 'int-nfr-5', question: 'HA and Redundancy considered?' },
      { id: 'int-nfr-6', question: 'DR requirements specified?' },
    ],
  },
  data: {
    'Metadata & Lifecycle': [
      { id: 'data-meta-1', question: 'Data classification and ownerships documented?' },
      { id: 'data-meta-2', question: 'Data usage/management RnR defined?' },
      { id: 'data-meta-3', question: 'Data lifecycle established?' },
      { id: 'data-meta-4', question: 'Data sources and data model documentation maintained?' },
      { id: 'data-meta-5', question: 'Technology stack documented?' },
      { id: 'data-meta-6', question: 'EoS, EoL, Version upgrades, Platform upgrades tracked?' },
    ],
  },
  infrastructure: {
    'Metadata & Lifecycle': [
      { id: 'infra-meta-1', question: 'Adequacy of environments, platforms and runtimes assessed?' },
      { id: 'infra-meta-2', question: 'Platform upgrades, EoS, EoL tracked?' },
      { id: 'infra-meta-3', question: 'Demand, capacity requirements, YoY Growth documented?' },
      { id: 'infra-meta-4', question: 'Adequacy of bandwidths for compute, storage and network verified?' },
    ],
    'Security': [
      { id: 'infra-sec-1', question: 'Authentication, AuthZ implemented?' },
      { id: 'infra-sec-2', question: 'RBAC configured?' },
      { id: 'infra-sec-3', question: 'Key Vault used?' },
      { id: 'infra-sec-4', question: 'PKI, Encryption implemented?' },
      { id: 'infra-sec-5', question: 'Certs managed?' },
      { id: 'infra-sec-6', question: 'VAPT, End point protection in place?' },
      { id: 'infra-sec-7', question: 'Standards and Legal compliance verified?' },
      { id: 'infra-sec-8', question: 'Integration security implemented?' },
    ],
    'Others': [
      { id: 'infra-oth-1', question: 'Automation, IaaC implemented?' },
      { id: 'infra-oth-2', question: 'Audits/Logging configured?' },
      { id: 'infra-oth-3', question: 'Monitoring, Alerts set up?' },
      { id: 'infra-oth-4', question: 'TCO – 3yrs, 5yrs calculated?' },
      { id: 'infra-oth-5', question: 'Integrations – QoS defined?' },
      { id: 'infra-oth-6', question: 'Distributed Cache required?' },
      { id: 'infra-oth-7', question: 'Notifications/Events implemented?' },
      { id: 'infra-oth-8', question: 'Scheduled Jobs/Batches documented?' },
    ],
  },
  devsecops: {
    'DevOps': [
      { id: 'devops-1', question: '12 Factor compliance verified?' },
      { id: 'devops-2', question: 'Version control and branching strategy defined?' },
      { id: 'devops-3', question: 'CI-CD pipeline, toolset established?' },
      { id: 'devops-4', question: 'Identity access mgmt. configured?' },
      { id: 'devops-5', question: 'Secrets & Config mgmt. implemented?' },
      { id: 'devops-6', question: 'Build and packaging automated?' },
      { id: 'devops-7', question: 'Deployment strategy & release mgmt. defined?' },
      { id: 'devops-8', question: 'Templatization, IaaC implemented?' },
    ],
    'SecOps': [
      { id: 'secops-1', question: 'Threat models and mitigations documented?' },
      { id: 'secops-2', question: 'Secure code reviews conducted?' },
      { id: 'secops-3', question: 'Static code analysis – SAST integrated?' },
      { id: 'secops-4', question: 'DAST implemented?' },
      { id: 'secops-5', question: 'VAPT completed?' },
      { id: 'secops-6', question: 'Environments hardening applied?' },
      { id: 'secops-7', question: 'SW Hardening implemented?' },
      { id: 'secops-8', question: 'Metrics reporting in place?' },
    ],
    'Engineering Excellence & SW Quality': [
      { id: 'engex-1', question: 'Static code analysis implemented?' },
      { id: 'engex-2', question: 'LLD reviews conducted?' },
      { id: 'engex-3', question: 'Code reviews mandatory?' },
      { id: 'engex-4', question: 'Test plans reviews done?' },
      { id: 'engex-5', question: 'Defect tracking metrics defined?' },
      { id: 'engex-6', question: 'Automation testing implemented?' },
      { id: 'engex-7', question: 'API Testing conducted?' },
      { id: 'engex-8', question: 'Performance testing done?' },
      { id: 'engex-9', question: 'SW Quality metrics reporting in place?' },
    ],
  },
  nfr: {
    'Scalability & Performance': [
      { id: 'nfr-scalar-1', question: 'Number of users, YoY growth documented?' },
      { id: 'nfr-scalar-2', question: 'Number of concurrent users defined?' },
      { id: 'nfr-scalar-3', question: 'TPS / API calls per unit specified?' },
      { id: 'nfr-scalar-4', question: 'Response time (< 3 Sec)?' },
      { id: 'nfr-scalar-5', question: 'Long running use cases identified?' },
      { id: 'nfr-scalar-6', question: 'Batch / Scheduled jobs – peak-off peak considered?' },
    ],
    'HA & Resilience': [
      { id: 'nfr-ha-1', question: 'Any Single point of Failures?' },
      { id: 'nfr-ha-2', question: 'HA – Four 9s, Five 9s?' },
      { id: 'nfr-ha-3', question: 'Failover mechanism defined?' },
      { id: 'nfr-ha-4', question: 'DR, RPO, RTO documented?' },
      { id: 'nfr-ha-5', question: 'Error handling implemented?' },
      { id: 'nfr-ha-6', question: 'Self healing?' },
      { id: 'nfr-ha-7', question: 'Cache – Sync configured?' },
      { id: 'nfr-ha-8', question: 'Reliability, Extensibility, Maintainability considered?' },
    ],
    'Security': [
      { id: 'nfr-sec-1', question: 'Authentication, Authorization implemented?' },
      { id: 'nfr-sec-2', question: 'RBAC, IAM configured?' },
      { id: 'nfr-sec-3', question: 'Key Vault used?' },
      { id: 'nfr-sec-4', question: 'PKI, Encryption implemented?' },
      { id: 'nfr-sec-5', question: 'Certs managed?' },
      { id: 'nfr-sec-6', question: 'VAPT, End point protection in place?' },
      { id: 'nfr-sec-7', question: 'Standards and Legal compliance verified?' },
      { id: 'nfr-sec-8', question: 'Integration security implemented?' },
    ],
  },
}
